version: '2'
services:
    tasklist-app:
        image: tasklist
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://tasklist-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=tasklist
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tasklist-mongodb:
        extends:
            file: mongodb.yml
            service: tasklist-mongodb
